chore: add check for TARGET_VERSION
Signed-off-by: Justin Marquis <34fathombelow@protonmail.com>

diff --git a/.github/workflows/init-release.yaml b/.github/workflows/init-release.yaml
--- a/.github/workflows/init-release.yaml
+++ b/.github/workflows/init-release.yaml
@@ -29,6 +29,15 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           ref: ${{ inputs.TARGET_BRANCH }}
 
+      - name: Check if the TARGET_VERSION is well formed.
+        run: |
+          set -xue
+          # Target version must not contain 'v' prefix      
+          if echo "${{ inputs.TARGET_VERSION }}" | grep -e '^v'; then
+            echo "::error::Target version '${{ inputs.TARGET_VERSION }}' should not begin with a 'v' prefix, refusing to continue." >&2
+            exit 1
+          fi
+
       - name: Create VERSION information
         run: |
           set -ue
